### ISSUE TITLE
Unable to register or log in into the chat system 

### ISSUE THREAD

**Issue by Iffah07** [ShankyTiwari/Realtime-Private-Chat-using-Angular-Nodejs-and-Mysql#1]
Shows unsuccessful to log in

**Comment by ShankyTiwari** [comment]
Hi there,
Can you share some more information? Like if you are getting any error in Browser console or in Nodejs CMD console?

**Comment by Iffah07** [comment]
Hi this is what i got.

i tried to register with "example" as username and password and this is what the console showed


(node:13912) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
    --------------------
    at Protocol._enqueue (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\node_modules\mysql\lib\Pool.js:202:8)
    at Promise (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\utils\db.js:26:20)
    at new Promise (<anonymous>)
    at Db.query (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\utils\db.js:25:10)
    at Helper.userNameCheck (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\utils\helper.js:16:24)
    at app.post (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\utils\routes.js:26:31)
(node:13912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 1)
(node:13912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.{ Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
    --------------------
    at Protocol._enqueue (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\node_modules\mysql\lib\Pool.js:202:8)
    at Promise (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\utils\db.js:26:20)
    at new Promise (<anonymous>)
    at Db.query (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\utils\db.js:25:10)
    at Helper.registerUser (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\utils\helper.js:21:25)
    at app.post (C:\Users\User\Desktop\Realtime-Private-Chat-using-AngularJs-Nodejs-and-Mysql-master\utils\routes.js:56:33)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true }


________________________________

**Comment by ShankyTiwari** [comment]
Hey there, Please make sure your MySql server is running on ```127.0.0.1:3306```.
