### ISSUE TITLE
Configure Real time chat In live https server

### ISSUE THREAD

**Issue by pradeepmvenur** [ShankyTiwari/Realtime-Private-Chat-using-Angular-Nodejs-and-Mysql#3]
Hi Sir,

     "Realtime-Private-Chat-using-Angular-Nodejs-and-Mysql" project downloaded from github and try to configuring in live https domain eg(https://www.example.com). I changed localhost hostname to our hostname in server.js file. If i run cmd "node server.js" then am getting error like this 
"listen EADDRNOTAVAIL 52.177.172.131:3000
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1523:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
"
Can you please send me server.js file or help me where i need to change functionality to run this project  in live https domain

Waiting for your positive reply.

**Comment by ShankyTiwari** [comment]
Port 3000 is in use, please change the port.
